build:
  number: 2
  skip: True # [osx]

package:
    name: brass 
    version: 5.1.6
source:
    fn: 5.1.6.tar.gz
    url: https://github.com/cancerit/BRASS/archive/v5.1.6.tar.gz
    md5: bb33dec7048cd1634845f143ed706e3a
    patches:
       - makefile.patch
       - cansam_headers.patch

requirements:
  build:
    - gcc   # [not osx]
    - llvm  # [osx]
    - perl-pcap
    - perl-grass
    - cansam
    - boost
    - perl-extutils-makemaker
    - perl-app-cpanminus
    - perl-math-combinatorics
    - perl-bioperl-core
    - perl-bio-db-hts
    - perl-bio-featureio

  run:
    - libgcc
    - blat
    - velvet
    - exonerate
    - bedtools
    - cansam
    - perl-pcap
    - perl-grass
    - perl-math-combinatorics
    - perl-bioperl-core
    - perl-bio-db-hts
    - perl-bio-featureio

test:
  commands:
    - brass-group --help
    - brass.pl --help
